"""empty message

Revision ID: 775ec864451a
Revises: 0901c97f9b13
Create Date: 2019-03-10 01:37:21.685486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775ec864451a'
down_revision = '0901c97f9b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
